API development
ISIS3510-202410-Team33/ventura-backend pull request #4
Opened 2024-04-16 15:08 UTC by ObedCabanzo

Implementation of updating user's location frequency is not yet available

2024-04-16 15:14 UTC, c4ts0up requested changes
No tengo pruebas pero tampoco dudas.

2024-04-16 15:14 UTC, c4ts0up commented
Erase all the __pycache__ folders to prevent future issues

2024-04-16 16:00 UTC, c4ts0up approved these changes

2024-04-16 16:01 UTC, merged

2024-04-22 23:32 UTC, ObedCabanzo commented
files related with .gitifgnore were deleted manually